# Generated by Django 4.2 on 2023-05-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Oncology', 'Oncology'), ('Neurosurgery', 'Neurosurgery'), ('Orthopedic', 'Orthopedic'), ('E N T', 'E N T'), ('Radiology', 'Radiology'), (' Urology', ' Urology')], default='Doctor care', max_length=50),
        ),
    ]
