# Generated by Django 3.2.18 on 2023-05-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=250)),
                ('doc_degree', models.CharField(max_length=250)),
                ('doc_specialised', models.CharField(max_length=2500)),
                ('doc_language', models.CharField(max_length=2500)),
                ('doc_image', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='doctorss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=250)),
                ('doc_degree', models.CharField(max_length=250)),
                ('doc_specialised', models.CharField(max_length=2500)),
                ('doc_language', models.CharField(max_length=2500)),
                ('doc_image', models.CharField(max_length=2500)),
            ],
        ),
    ]
