# Generated by Django 3.2.18 on 2023-05-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctors',
        ),
    ]
